import numpy as np
import scipy as scp

default_gsmm_kwargs = {
    "init_coef": None,
    "max_outer": 200,
    "max_inner": 500,
    "min_inner": None,
    "conv_tol": 1e-7,
    "extend_lambda": False,
    "extension_method_lam": "expected_ratio",
    "control_lambda": None,
    "restart": False,
    "optimizer": "Newton",
    "method": "QR/Chol",
    "check_cond": 1,
    "piv_tol": np.power(np.finfo(float).eps, 0.04),
    "progress_bar": False,
    "n_cores": 0,
    "seed": 0,
    "drop_NA": True,
    "init_lambda": None,
    "form_VH": True,
    "build_mat": None,
    "should_keep_drop": True,
    "gamma": 1,
    "qEFSH": "SR1",
    "max_restarts": 0,
    "prefit_grad": True,
    "repara": True,
    "extra_penalties": None,
    "callback": None,
    "bfgs_options": None,
    "global_opt_qefs": False,
    "sample_hessian": True,
    "sample_hessian_method": 0,
    "sample_hessian_options": None,
    "structured_qefs": True,
    "structured_qefs_budget": 100,
    "sqEFS_options": {
            "dampen_HBB": 1e-7,
            "dampen_HBb": 1,
            "pre_cond": True,
            "PD_HBB": False,
        },
    "qEFS_memory_usage": 0.25,
}

default_gammlss_kwargs = {
    "max_outer": 200,
    "max_inner": 500,
    "min_inner": None,
    "conv_tol": 1e-7,
    "extend_lambda": False,
    "extension_method_lam": "expected_ratio",
    "control_lambda": 2,
    "restart": False,
    "method": "QR/Chol",
    "check_cond": 1,
    "piv_tol": np.power(np.finfo(float).eps, 0.04),
    "should_keep_drop": True,
    "prefit_grad": True,
    "repara": True,
    "progress_bar": False,
    "n_cores": 10,
    "seed": 0,
    "init_lambda": None,
}

default_gamm_kwargs = {
    "max_outer": 200,
    "max_inner": None,
    "conv_tol": 1e-7,
    "extend_lambda": False,
    "control_lambda": 2,
    "exclude_lambda": False,
    "extension_method_lam": "expected_ratio",
    "restart": False,
    "method": "QR",
    "check_cond": 1,
    "progress_bar": False,
    "n_cores": 10,
    "offset": None,
    "rho": None,
    "transform_X": None,
}

default_comparison_kwargs = {
    "correct_V": True,
    "correct_t1": False,
    "perform_GLRT": False,
    "nR": 250,
    "n_c": 1,
    "alpha": 0.05,
    "grid": "JJJ1",
    "a": 1e-7,
    "b": 1e7,
    "df": 40,
    "verbose": False,
    "drop_NA": True,
    "method": "Chol",
    "seed": None,
    "only_expected_edf": None,
    "Vp_fidiff": False,
    "use_importance_weights": None,
    "prior": None,
    "recompute_H": None,
    "compute_Vcc": True,
    "bfgs_options": {},
}
